### ISSUE TITLE
Fix typo in file NetworkAPI.swift

### ISSUE THREAD

**Issue by Andrej123** [cocoaheads-slovenija/charge-oclock#3]
In file NetworkAPI.swift there is a typo at line 28:
`// yes, explicit unwinding, if we fail here, it might as well be the end of the world!`
The correct text should be:
`// yes, explicit unwrapping, if we fail here, it might as well be the end of the world!`

**Comment by goranche** [comment]
true... go for it... 👍

**Comment by goranche** [comment]
fixed by #4
